DECISION_NONE = b'.'
DECISIONBASIS_MISMATCH = b'M'
DECISION_KEEP_AS_KEY = b'K'
DECISION_REVEAL_AS_0 = b'Z'
DECISION_REVEAL_AS_1 = b'O'

COMPARISON_NONE = b'.'
COMPARISON_SAME = b'S'
COMPARISON_DIFFERENT = b'D'

BASIS_COMPUTATIONAL = b'+'
BASIS_HADAMARD = b'x'

ACK = b'A'
